PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX dc11: <http://purl.org/dc/elements/1.1/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX ex: <http://example.com/>

SELECT ?doelOV ?onderwerp ?niveau ?org
WHERE {
  ?doelOV a <http://data.europa.eu/snb/model/elm/LearningAchievement> ;
    dc11:creator ex:OV; ;
    ex:eigenCombinatieLeerdoelOpleidingsniveau ?collectie ;
    dc11:subject ex:SC_6 .
  ex:SC_6 ex:shortLabel ?onderwerp .
  ?collectie dcterms:title ?collectieNaam;
               ex:niveau ex:S-gr2-DoF.
  ex:S-gr2-DoF dcterms:title ?niveau
  VALUES ?_org {ex:KaO ex:GO}
  ?_org dcterms:title ?org .
  FILTER NOT EXISTS {
    ?_anderDoel skos:broader|skos:closeMatch|skos:narrower ?doelOV ;
                dc11:creator ?_org .
  }
}
