PREFIX dc11: <http://purl.org/dc/elements/1.1/>
PREFIX ex: <http://example.com/>

SELECT DISTINCT ?doelOV
WHERE {
  ?doelOV a <http://data.europa.eu/snb/model/elm/LearningAchievement> ;
    dc11:creator ex:OV .
}
